modLoader="javafml"
loaderVersion="[39,)"
license="LGPLv2"
issueTrackerURL="https://github.com/xfacthd/norender/"

[[mods]]
	modId="norender"
	version="${file.jarVersion}"
	displayName="NoRender"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
	logoFile="logo.png"
	credits="Thanks for this example mod goes to Java"
	authors="Love, Cheese and small house plants"
	description='''
	'''

[[dependencies.norender]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.norender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
