modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/xfacthd/norender/"

[[mods]]
	modId="norender"
	version="${file.jarVersion}"
	displayName="NoRender"
    displayTest="IGNORE_ALL_VERSION"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
	logoFile="logo.png"
	#credits="Thanks for this example mod goes to Java"
	authors="XFactHD"
	description='''
	'''

[[dependencies.norender]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.norender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
