modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPLv3"
issueTrackerURL="https://github.com/xfacthd/norender/"

[[mods]]
	modId="norender"
	version="${mod_version}"
	displayName="NoRender"
    displayTest="IGNORE_ALL_VERSION"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/norender"
	logoFile="logo.png"
	authors="XFactHD"
	description='''
	'''

[[dependencies.norender]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.norender]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
